export const NATIONALITIES = [
    { value: '', label: '--- Please Select ---' },
    { value: 'AFG', label: 'Afghanistan' },
    { value: 'AL', label: 'Albania' },
    { value: 'DZ', label: 'Algeria' },
    { value: 'GBA', label: 'ALDERNEY (CHANNEL ISLANDS)' },
    { value: 'AND', label: 'Andorra' },
    { value: 'ATG', label: 'Antigua and Barbuda' },
    { value: 'RA', label: 'Argentina' },
    { value: 'AU1', label: 'Australia' },
    { value: 'AUS', label: 'Australia' },
    { value: 'A', label: 'Austria' },
    { value: 'BS', label: 'Bahamas' },
    { value: 'BRN', label: 'Bahrain' },
    { value: 'BD', label: 'Bangladesh' },
    { value: 'BDS', label: 'Barbados' },
    { value: 'BY', label: 'Belarus' },
    { value: 'B', label: 'Belgium' },
    { value: 'BH', label: 'Belize' },
    { value: 'DY', label: 'Benin' },
    { value: 'BER', label: 'Bermuda' },
    { value: 'BHU', label: 'BHUTAN' },
    { value: 'BOL', label: 'Bolivia' },
    { value: 'RB', label: 'Botswana' },
    { value: 'BR', label: 'Brazil' },
    { value: 'BRU', label: 'Brunei' },
    { value: 'BG', label: 'Bulgaria' },
    { value: 'BU', label: 'Burma' },
    { value: 'K', label: 'Cambodia' },
    { value: 'CDN', label: 'Canada' },
    { value: 'RCA', label: 'CENTRAL AFRICAN REPUBLIC' },
    { value: 'RCH', label: 'Chile' },
    { value: 'CHI', label: 'China' },
    { value: 'CO', label: 'Colombia' },
    { value: 'RCB', label: 'Congo, Republic of the' },
    { value: 'CR', label: 'Costa Rica' },
    { value: 'COT', label: "Cote d'Ivoire" },
    { value: 'HR', label: 'Croatia' },
    { value: 'CY', label: 'Cyprus' },
    { value: 'CZ', label: 'Czech Republic' },
    { value: 'DK', label: 'Denmark' },
    { value: 'DJI', label: 'Djibouti' },
    { value: 'WD', label: 'Dominica' },
    { value: 'DOM', label: 'Dominican Republic' },
    { value: 'EC', label: 'Ecuador' },
    { value: 'ET', label: 'Egypt' },
    { value: 'ES', label: 'El Salvador' },
    { value: 'EW', label: 'Estonia' },
    { value: 'ETH', label: 'Ethiopia' },
    { value: 'FR', label: 'Faroe Islands' },
    { value: 'FJI', label: 'Fiji' },
    { value: 'FIN', label: 'Finland' },
    { value: 'F', label: 'France' },
    { value: 'GAB', label: 'Gabon' },
    { value: 'D', label: 'Germany' },
    { value: 'GH', label: 'Ghana' },
    { value: 'GBZ', label: 'Gibraltar' },
    { value: 'GR', label: 'Greece' },
    { value: 'WG', label: 'Grenada' },
    { value: 'GBR', label: 'GREAT BRITAIN' },
    { value: 'GUA', label: 'Guam' },
    { value: 'GCA', label: 'Guatemala' },
    { value: 'GBG', label: 'Guernsey' },
    { value: 'GU', label: 'Guinea' },
    { value: 'GUI', label: 'Guinea-Bissau' },
    { value: 'GUY', label: 'Guyana' },
    { value: 'RH', label: 'Haiti' },
    { value: 'HON', label: 'Honduras' },
    { value: 'HKG', label: 'Hong Kong' },
    { value: 'H', label: 'Hungary' },
    { value: 'IS', label: 'Iceland' },
    { value: 'INA', label: 'India' },
    { value: 'IND', label: 'Indonesia' },
    { value: 'IRL', label: 'Ireland' },
    { value: 'GBM', label: 'Isle of Man' },
    { value: 'IL', label: 'Israel' },
    { value: 'I', label: 'Italy' },
    { value: 'CI', label: 'Ivory Coast' },
    { value: 'JA', label: 'Jamaica' },
    { value: 'JAP', label: 'Japan' },
    { value: 'GBJ', label: 'Jersey' },
    { value: 'JOR', label: 'Jordan' },
    { value: 'KAZ', label: 'Kazakhstan' },
    { value: 'EAK', label: 'Kenya' },
    { value: 'KOR', label: 'Korea, South' },
    { value: 'KWT', label: 'Kuwait' },
    { value: 'KYR', label: 'Kyrgyzstan' },
    { value: 'LAO', label: 'Laos' },
    { value: 'LV', label: 'Latvia' },
    { value: 'RL', label: 'Lebanon' },
    { value: 'LS', label: 'Lesotho' },
    { value: 'LAR', label: 'Libya' },
    { value: 'FL', label: 'Liechtenstein' },
    { value: 'LT', label: 'Lithuania' },
    { value: 'LON', label: 'London' },
    { value: 'L', label: 'Luxembourg' },
    { value: 'MAC', label: 'Macau' },
    { value: 'MK', label: 'Macedonia' },
    { value: 'RM', label: 'Madagascar' },
    { value: 'MW', label: 'Malawi' },
    { value: 'MAL', label: 'Malaysia' },
    { value: 'MDV', label: 'Maldives' },
    { value: 'RMM', label: 'Mali' },
    { value: 'M', label: 'Malta' },
    { value: 'RIM', label: 'Mauritania' },
    { value: 'MS', label: 'Mauritius' },
    { value: 'MEX', label: 'Mexico' },
    { value: 'MC', label: 'Monaco' },
    { value: 'MO3', label: 'Mongolia' },
    { value: 'MOT', label: 'Montserrat' },
    { value: 'MA', label: 'Morocco' },
    { value: 'MOZ', label: 'Mozambique' },
    { value: 'BUR', label: 'Myanmar (Burma)' },
    { value: 'NE3', label: 'Nepal' },
    { value: 'NL', label: 'Netherlands' },
    { value: 'NA', label: 'Netherlands Antilles' },
    { value: 'NEW', label: 'New Caledonia' },
    { value: 'NZ1', label: 'New Zealand' },
    { value: 'NIC', label: 'Nicaragua' },
    { value: 'RN', label: 'Niger' },
    { value: 'WAN', label: 'Nigeria' },
    { value: 'N', label: 'Norway' },
    { value: 'OMA', label: 'Oman' },
    { value: 'PK', label: 'Pakistan' },
    { value: 'PAL', label: 'Palestine' },
    { value: 'PA', label: 'Panama' },
    { value: 'PAP', label: 'Papua New Guinea' },
    { value: 'PY', label: 'Paraguay' },
    { value: 'PE', label: 'Peru' },
    { value: 'RP', label: 'Philippines' },
    { value: 'PL', label: 'Poland' },
    { value: 'P', label: 'Portugal' },
    { value: 'QAT', label: 'Qatar' },
    { value: 'RO', label: 'Romania' },
    { value: 'RUS', label: 'Russia' },
    { value: 'RWA', label: 'Rwanda' },
    { value: 'SAI', label: 'Saipan' },
    { value: 'WS', label: 'Samoa' },
    { value: 'RSM', label: 'San Marino' },
    { value: 'SAU', label: 'Saudi Arabia' },
    { value: 'SKN', label: 'SAINT KITTS AND NEVIS' },
    { value: 'SLC', label: 'SAINT LUCIA' },
    { value: 'SN', label: 'Senegal' },
    { value: 'SER', label: 'Serbia and Montenegro' },
    { value: 'SY', label: 'Seychelles' },
    { value: 'SGP', label: 'Singapore' },
    { value: 'SK', label: 'Slovakia' },
    { value: 'SP', label: 'Somalia' },
    { value: 'ZA', label: 'South Africa' },
    { value: 'E', label: 'Spain' },
    { value: 'SLK', label: 'Sri Lanka' },
    { value: 'SUD', label: 'Sudan' },
    { value: 'SME', label: 'Suriname' },
    { value: 'SD', label: 'Swaziland' },
    { value: 'S', label: 'Sweden' },
    { value: 'CH', label: 'Switzerland' },
    { value: 'TAI', label: 'Taiwan' },
    { value: 'EAT', label: 'Tanzania' },
    { value: 'T', label: 'Thailand' },
    { value: 'WAG', label: 'THE GAMBIA' },
    { value: 'TL', label: 'TIMOR-LESTE' },
    { value: 'TG', label: 'Togo' },
    { value: 'TT', label: 'Trinidad and Tobago' },
    { value: 'TN', label: 'Tunisia' },
    { value: 'TR', label: 'Turkey' },
    { value: 'TMN', label: 'Turkmenistan' },
    { value: 'EAU', label: 'Uganda' },
    { value: 'UA', label: 'Ukraine' },
    { value: 'VAE', label: 'United Arab Emirates' },
    { value: 'UK', label: 'United Kingdom' },
    { value: 'USA', label: 'United States' },
    { value: 'ROU', label: 'Uruguay' },
    { value: 'UZB', label: 'Uzbekistan' },
    { value: 'VUT', label: 'VANUATU' },
    { value: 'YV', label: 'Venezuela' },
    { value: 'VN', label: 'Vietnam' },
    { value: 'ADN', label: 'Yemen' },
    { value: 'YU', label: 'Yugoslavia' },
    { value: 'ZM', label: 'Zambia' },
    { value: 'ZW', label: 'Zimbabwe' }
  ];