export const OCCPSECS = [
    { value: '', label: '--- Please Select ---' },
    { value: 'FW25', label: 'AGRICULTURE - GENERAL WORKERS' },
    { value: 'FW04', label: 'BREEDING - GENERAL WORKERS' },
    { value: 'FW23', label: 'CONSTRUCTION - GENERAL WORKERS' },
    { value: 'FW07', label: 'DOMESTIC MAID' },
    { value: 'FW03', label: 'ELECTRICITY, GAS & WATER SUPPLY - GENERAL WORKERS' },
    { value: 'FW09', label: 'FISHERY - GENERAL WORKERS' },
    { value: 'FW22', label: 'FORESTRY - GENERAL WORKERS' },
    { value: 'FW02', label: 'HUNTING - GENERAL WORKERS' },
    { value: 'FW06', label: 'MANUFACTURING - OTHER GENERAL WORKERS' },
    { value: 'FW05', label: 'MANUFACTURING - PRODUCTION OPERATORS' },
    { value: 'FW01', label: 'MINING & QUARRYING - GENERAL WORKERS' },
    { value: 'FW12', label: 'PERSONAL & HOUSEHOLD GOODS - GENERAL WORKERS' },
    { value: 'FW24', label: 'PLANTATION - GENERAL WORKERS' },
    { value: 'FW11', label: 'REPAIR OF MOTOR VEHICLES - GENERAL WORKERS' },
    { value: 'FW15', label: 'SERVICES - CLEANING SERVICES - GENERAL WORKERS' },
    { value: 'FW18', label: 'SERVICES - HAIRDRESSING/BARBER - GENERAL WORKERS' },
    { value: 'FW16', label: 'SERVICES - ISLAND RESORT - GENERAL WORKERS' },
    { value: 'FW20', label: 'SERVICES - OTHERS - GENERAL WORKERS' },
    { value: 'FW19', label: 'SERVICES - SECURITY SERVICES - GENERAL WORKERS' },
    { value: 'FW17', label: 'SERVICES - WELFARE HOMES - GENERAL WORKERS' },
    { value: 'FW13', label: 'SERVICES - HOTEL & RESTAURANT - GENERAL WORKERS' },
    { value: 'FW14', label: 'SERVICES - LAUNDRY - GENERAL WORKERS' },
    { value: 'FW08', label: 'TRANSPORT, STORAGE & COMMUNICATION - GENERAL WORKERS' },
    { value: 'FW10', label: 'WHOLESALE & RETAIL TRADE - GENERAL WORKERS' },
  ];
  