export const OCCUPATION_CODES = [
    { value: '', label: '--- Please Select ---' },
    { value: '0006', label: 'ACADEMIC' },
    { value: 'M011', label: 'ACADEMIC/EDUCATOR' },
    { value: '0018', label: 'ACADEMY COUNSELOR' },
    { value: '0007', label: 'ACCESSORIES WORK' },
    { value: '0003', label: 'ACCESSORY SHOP OWNER' },
    { value: '0001', label: 'ACCOUNTANT' },
    { value: '0013', label: 'ACCOUNTS ASSISTANT' },
    { value: '0010', label: 'ACCOUNTS AUDITOR' },
    { value: '0014', label: 'ACCOUNTS CLERK' },
    { value: '0015', label: 'ACCOUNTS CONTROLLER' },
    { value: '0016', label: 'ACCOUNTS DIRECTOR' },
    { value: '0017', label: 'ACCOUNTS EXECUTIVE/MARKETING' },
    { value: '0009', label: 'ACCOUNTS MANAGER' },
    { value: '0008', label: 'ACCOUNTS OFFICER' },
    { value: '0011', label: 'ACCOUNTS SUPERVISOR' },
    { value: '0019', label: 'ACTOR' },
    { value: 'M012', label: 'ACTOR/ACTRESS/ENTERTAINERS' },
    { value: '0020', label: 'ACTUARIAL OFFICER' },
    { value: '0021', label: 'ADJUSTER' },
    { value: '0012', label: 'ADMIN & ACCOUNTS/DIRECTOR' },
    { value: '0025', label: 'ADMIN & DIPLOMATIC OFFICER' },
    { value: '0029', label: 'ADMIN DIRECTOR / OFFICER' },
    { value: '0027', label: 'ADMIN EXECUTIVE' },
    { value: '0024', label: 'ADMIN MANAGER' },
    { value: '0370', label: 'ADMINISTRATIVE CLERK' },
    { value: '1653', label: 'ADMINISTRATIVE OFFICER' },
    { value: '0030', label: 'ADMINSTRATIVE / ASSISTANT' },
    { value: '0028', label: 'ADVERTISING' },
    { value: '1675', label: 'ADVERTISING - OUTDOOR' },
    { value: '1676', label: 'ADVERTISING DIRECTOR' },
    { value: '1677', label: 'ADVERTISING FIRM MANAGER' },
    { value: '1678', label: 'ADVERTISING MARKETING' },
    { value: '1679', label: 'ADVERTISING RAW MATERIAL' },
    { value: '1680', label: 'ADVERTISING REPRESENTATIVE' },
    { value: '1674', label: 'ADVERTISMENT / ADVERTISER' },
    { value: '1803', label: 'ADVISER' },
    { value: '0022', label: 'ADVISOR' },
    { value: '0023', label: 'ADVOCATES & SOLICITORS' },
    { value: '0031', label: 'AGENCY' },
    { value: '1289', label: 'AGENCY MANAGER / SUPERVISOR' },
    { value: '0004', label: 'AGENT/COMMISION AGENT' },
    { value: '0034', label: 'AGRICULTURE' },
    { value: '1650', label: 'AGRICULTURE OFFICER' },
    { value: '0035', label: 'AGRONOMIST' },
    { value: '1332', label: 'AIR CRAFT MECHANIC' },
    { value: '1334', label: 'AIR CRAFT TECHNICAL/TECHNICIAN' },
    { value: '1681', label: 'AIR EXPORT OPERATIONS' },
    { value: '1682', label: 'AIR FORWARDING AGENT' },
    { value: '1683', label: 'AIR PURIFYING' },
    { value: '1684', label: 'AIR TRAFFIC CONTROLLER' },
    { value: '1327', label: 'AIR-COND & ELECTRICAL SERVICES' },
    { value: '1328', label: 'AIR-COND & WIRING WORKS' },
    { value: '0038', label: 'AIR-COND DEALER / CONTRACTOR' },
    { value: '1330', label: 'AIR-COND MECHANIC' },
    { value: '1323', label: 'AIR-COND REPAIRER / TECHNICIAN' },
    { value: '1322', label: 'AIR-COND SERVICES' },
    { value: '1324', label: 'AIR-COND SPECIALIST' },
    { value: '1329', label: 'AIR-COND TECHNICIAN' },
    { value: '1326', label: 'AIR-COND TECHNICIAN/ENGINEER' },
    { value: '1325', label: 'AIR-CONDITIONER' },
    { value: '0041', label: 'AIR-FORCE' },
    { value: '1335', label: 'AIR-FORCE OFFICER' },
    { value: '1331', label: 'AIRCRAFT ENGINEER' },
    { value: '1686', label: 'AIRLINE EXECUTIVE' },
    { value: '1336', label: 'AIRLINE MANAGER' },
    { value: '1687', label: 'AIRLINE OFFICER' },
    { value: '1688', label: 'AIRLINE TICKETING OFFICER' },
    { value: '0043', label: 'AIRLINES' },
    { value: '0042', label: 'AIRPORT FIREMAN' },
    { value: '1689', label: 'AIRPORT OFFICER' },
    { value: '0005', label: 'AIRPORT OPERATION/STAFF' },
    { value: '1690', label: 'AIRPORT TAXI' },
    { value: '1338', label: 'ALUMINIUM DECORATION' },
    { value: '0045', label: 'ALUMINIUM WORKS' },
    { value: '0046', label: 'AMBASSADOR' },
    { value: '0048', label: 'ANALYST' },
    { value: '1339', label: 'ANALYST PROGRAMMER' },
    { value: '1340', label: 'APPLICATION ANALYST' },
    { value: '1342', label: 'APPLICATION ENGINEER' },
    { value: '1343', label: 'APPLICATION SPECIALIST' },
    { value: '0050', label: 'AQUACULTURIST' },
    { value: '0051', label: 'AQUARIUM OWNER' },
    { value: '0052', label: 'ARCHITECT' },
    { value: '0053', label: 'ARCHITECT FIRM' },
    { value: '1345', label: 'ARCHITECTURAL TECHNICIAN' },
    { value: '0054', label: 'ARCHITECTURE' },
    { value: '1346', label: 'ARCHITECTURE COORDINATOR' },
    { value: '1344', label: 'ARCHITECTURE DESIGNER' },
    { value: '1347', label: 'AREA MANAGER' },
    { value: '1348', label: 'ARMED FORCES' },
    { value: '0056', label: 'ARMY' },
    { value: '1349', label: 'ARMY OFFICER' },
    { value: '1350', label: 'ART CREATIVE HEAD' },
    { value: '0057', label: 'ART DESIGNER' },
    { value: '1351', label: 'ART DIRECTOR' },
    { value: '0058', label: 'ARTIST / ARTISTIC DIRECTOR' },
    { value: '0059', label: 'ASSEMBLER' },
    { value: '1352', label: 'ASSEMBLING OF MOTOR CYCLES/COM' },
    { value: '1353', label: 'ASSEMBLY MANAGER' },
    { value: '0060', label: 'ASSESSOR' },
    { value: '1354', label: 'ASSIGNMENT EDITOR' },
    { value: '1355', label: 'ASSIST OFFICER PROCESS CONTROL' },
    { value: '0062', label: 'ASSISTANT' },
    { value: '0063', label: 'ASSISTANT ACCOUNTANT' },
    { value: '0064', label: 'ASSISTANT ACCOUNTS MANAGER' },
    { value: '0065', label: 'ASSISTANT ADMINISTRATION' },
    { value: '1665', label: 'ASSISTANT AGRICULTURE' },
    { value: '0066', label: 'ASSISTANT ARCHITECT' },
    { value: '0067', label: 'ASSISTANT BRANCH MANAGER' },
    { value: '0142', label: 'ASSISTANT BRANCH OFFICER' },
    { value: '0068', label: 'ASSISTANT CHARGEMAN' },
    { value: '1656', label: 'ASSISTANT CLERK' },
    { value: '1659', label: 'ASSISTANT CLINIC' },
    { value: '0887', label: 'ASSISTANT COMMISSIONER POLICE' },
    { value: '0070', label: 'ASSISTANT COMPANY SECRETARY' },
    { value: '0071', label: 'ASSISTANT CONSULTANT' },
    { value: '0072', label: 'ASSISTANT CUSTOMER ENGINEER' },
    { value: '0073', label: 'ASSISTANT CUSTOMER SERVICE' },
    { value: '0074', label: 'ASSISTANT DENTIST' },
    { value: '0075', label: 'ASSISTANT DIRECTOR' },
    { value: '1667', label: 'ASSISTANT DIRECTOR EDUCATION' },
    { value: '0076', label: 'ASSISTANT DISTRICT OFFICER' },
    { value: '0077', label: 'ASSISTANT DOCTOR' },
    { value: '0079', label: 'ASSISTANT EDP MANAGER' },
    { value: '0080', label: 'ASSISTANT EDUCATION OFFICER' },
    { value: '0894', label: 'ASSISTANT ENFORCEMENT' },
    { value: '0081', label: 'ASSISTANT ENFORCEMENT OFFICER' },
    { value: '0082', label: 'ASSISTANT ENGINEER' },
    { value: '0083', label: 'ASSISTANT EXECUTIVE' },
    { value: '0085', label: 'ASSISTANT FINANCIAL CONTROLLER' },
    { value: '0084', label: 'ASSISTANT FOREMAN' },
    { value: '0086', label: 'ASSISTANT GENERAL MANAGER' },
    { value: '0087', label: 'ASSISTANT HEAD MASTER' },
    { value: '0088', label: 'ASSISTANT HOUSEKEEPER' },
    { value: '0089', label: 'ASSISTANT HUMAN RESOURCE' },
    { value: '0115', label: 'ASSISTANT LEADER' },
    { value: '0090', label: 'ASSISTANT LECTURER' },
    { value: '0091', label: 'ASSISTANT LOGISTICS' },
    { value: '0092', label: 'ASSISTANT MACHINE OPERATOR' },
    { value: '0093', label: 'ASSISTANT MANAGER' },
    { value: '1357', label: 'ASSISTANT MANAGER CLAIMS' },
    { value: '1358', label: 'ASSISTANT MANAGER FINANCE' },
    { value: '0094', label: 'ASSISTANT MANAGING DIRECTOR' },
    { value: '0095', label: 'ASSISTANT MARKETING' },
    { value: '0097', label: 'ASSISTANT MARKETING MANAGER' },
    { value: '0143', label: 'ASSISTANT MEDICAL LAB' },
    { value: '0098', label: 'ASSISTANT MEDICAL OFFICER' },
    { value: '0099', label: 'ASSISTANT OFFICER' },
    { value: '0100', label: 'ASSISTANT OPERATION MANAGER' },
    { value: '0101', label: 'ASSISTANT OPERATOR' },
    { value: '0102', label: 'ASSISTANT PHARMACY' },
    { value: '0103', label: 'ASSISTANT PRESIDENT' },
    { value: '0104', label: 'ASSISTANT PRISON CONTROLLER' },
    { value: '0105', label: 'ASSISTANT PRODUCT ENGINEER' },
    { value: '0106', label: 'ASSISTANT PRODUCTION MANAGER' },
    { value: '0107', label: 'ASSISTANT PROFESSOR' },
    { value: '0108', label: 'ASSISTANT PROJECT MANAGER' },
    { value: '0109', label: 'ASSISTANT PURCHASING MANAGER' },
    { value: '0110', label: 'ASSISTANT REGISTRAR' },
    { value: '0111', label: 'ASSISTANT RESTAURANT MANAGER' },
    { value: '1657', label: 'ASSISTANT SAFETY OFFICER' },
    { value: '0112', label: 'ASSISTANT SALES EXECUTIVE' },
    { value: '0113', label: 'ASSISTANT SALES MANAGER' },
    { value: '0114', label: 'ASSISTANT SALES MARKETING' },
    { value: '0116', label: 'ASSISTANT SECRETARY' },
    { value: '0117', label: 'ASSISTANT SECURITY MANAGER' },
    { value: '0118', label: 'ASSISTANT SECURITY SUPERVISOR' },
    { value: '0119', label: 'ASSISTANT SERVICE MANAGER' },
    { value: '0123', label: 'ASSISTANT SHOP' },
    { value: '0120', label: 'ASSISTANT SITE MANAGER' },
    { value: '0121', label: 'ASSISTANT SPORT OFFICER' },
    { value: '0122', label: 'ASSISTANT STOREKEEPER' },
    { value: '0125', label: 'ASSISTANT SUPERVISOR' },
    { value: '0126', label: 'ASSISTANT TAX MANAGER' },
    { value: '0128', label: 'ASSISTANT TECHNICAL MANAGER' },
    { value: '0129', label: 'ASSISTANT TECHNICIAN' },
    { value: '0130', label: 'ASSISTANT TRAINER' },
    { value: '0131', label: 'ASSISTANT VALUER' },
    { value: '0132', label: 'ASSISTANT VICE PRESIDENT' },
    { value: '0133', label: 'ASSISTANT WARDEN' },
    { value: '0135', label: 'ASSOCIATE CONSULTANT' },
    { value: '0136', label: 'ASSOCIATE DIRECTOR' },
    { value: '1360', label: 'ASSOCIATE DIRECTOR CORPORATE' },
    { value: '0137', label: 'ASSOCIATE ENGINEER' },
    { value: '0138', label: 'ASSOCIATE PROFESSOR' },
    { value: '0139', label: 'ASSOCIATE TECHNICAL SUPPORT' },
    { value: '0140', label: 'ASSOCIATION EXECUTIVE' },
    { value: '1356', label: 'ASST SUPERINTENDANT OF CUSTOM' },
    { value: '0124', label: 'ASST SUPERINTENDENT POLICE' },
    { value: '0141', label: 'ASST.CHIEF FACTORY' },
    { value: '0145', label: 'ATHLETE' },
    { value: '0146', label: 'ATTENDANT' },
    { value: '0147', label: 'AUCTIONER' },
    { value: '0148', label: 'AUDIO COMPONENT MANUFACTURER' },
    { value: '0149', label: 'AUDIO TECHNICIAN' },
    { value: '1362', label: 'AUDIO VIDEO MANUFACTURER' },
    { value: '0150', label: 'AUDIT ASSISTANT' },
    { value: '0151', label: 'AUDIT ASSOCIATE' },
    { value: '0152', label: 'AUDIT EXECUTIVE' },
    { value: '0153', label: 'AUDIT MANAGER' },
    { value: '0154', label: 'AUDITOR' },
    { value: '1363', label: 'AUDITOR' },
    { value: '1518', label: 'AUDITOR' },
    { value: '0155', label: 'AUTO ACCESSORIES SHOP' },
    { value: '0156', label: 'AUTO AIR-COND SUPPLIER' },
    { value: '0157', label: 'AUTO REPAIRER' },
    { value: '0158', label: 'AUTO SPARE PARTS DEALER' },
    { value: '1364', label: 'AUTO SPARE PARTS SERVICES' },
    { value: '1365', label: 'AUTO SPARE PARTS SUPPLIER' },
    { value: '1366', label: 'AUTO SPRAY PAINTING' },
    { value: '0159', label: 'AUTO SPRAYER' },
    { value: '0160', label: 'AUTOMATION ENGINEER' },
    { value: '0161', label: 'AUTOMOTIVE' },
    { value: '1367', label: 'AUXILIARY POLICE PETRONAS' },
    { value: '0162', label: 'AUXILIARY POLICE SARGENT' },
    { value: '0164', label: 'AVIATION' },
    { value: '0166', label: 'BABY PRODUCTS SHOP' },
    { value: '1368', label: 'BABYSITTER' },
    { value: '0167', label: 'BABYSITTER / CARE TAKER' },
    { value: '1370', label: 'BACKHOE / EXCAVATOR DRIVER' },
    { value: '0171', label: 'BAG MAKER / MANUFACTURER' },
    { value: '1371', label: 'BAKER' },
    { value: '1372', label: 'BAKER SELLER' },
    { value: '0174', label: 'BAKERY' },
    { value: '1373', label: 'BAKERY MAKER' },
    { value: '0177', label: 'BANK ADMIN / BANK CLERK' },
    { value: '0178', label: 'BANK CONSULTANT' },
    { value: '0179', label: 'BANK EXECUTIVE' },
    { value: '0180', label: 'BANK MANAGER' },
    { value: '0181', label: 'BANK OFFICER' },
    { value: '0182', label: 'BANK TELLER' },
    { value: '0183', label: 'BANKER' },
    { value: '0184', label: 'BANKING BUREAU' },
    { value: '1376', label: 'BAR CAPTAIN' },
    { value: '0185', label: 'BAR TENDER' },
    { value: '0186', label: 'BARBER' },
    { value: '0187', label: 'BARRISTER' },
    { value: '0189', label: 'BASE COORDINATOR' },
    { value: '1379', label: 'BATIK DEALER' },
    { value: '0191', label: 'BEAUTICIAN' },
    { value: '1380', label: 'BEAUTY ADVISOR / DEV. MANAGER' },
    { value: '0192', label: 'BEAUTY CONSULTANT' },
    { value: '0193', label: 'BEAUTY SALOON' },
    { value: '1382', label: 'BEAUTY SALOON PARTNER' },
    { value: '1381', label: 'BEAUTY THERAPIST' },
    { value: '0198', label: 'BEVERAGE & FOODSTUFF TRADER' },
    { value: '1384', label: 'BICYCLE & FISHING TACKLE PART' },
    { value: '0199', label: 'BICYCLE DEALER' },
    { value: '1383', label: 'BICYCLE REPAIRER' },
    { value: '0200', label: 'BILLING CLERK' },
    { value: '0201', label: 'BINDING COMPANY' },
    { value: '0202', label: 'BIOTECNOLOGIST' },
    { value: '0203', label: 'BIRD NEST DEALER' },
    { value: '0204', label: 'BISHOP' },
    { value: '0205', label: 'BLACKSMITH' },
    { value: '0206', label: 'BLIND OPERATOR' },
    { value: '0208', label: 'BOARDCASTING' },
    { value: '0209', label: 'BOAT SERVICES' },
    { value: '0210', label: 'BOATMAN' },
    { value: '0211', label: 'BODY GUARD' },
    { value: '0212', label: 'BOILERMAN' },
    { value: '0213', label: 'BOLTS & FASTENERS' },
    { value: '0215', label: 'BOMOH' },
    { value: '0216', label: 'BOOK BINDER' },
    { value: '0217', label: 'BOOK DISTRIBUTOR' },
    { value: '0218', label: 'BOOK SALESMAN / SELLER' },
    { value: '0220', label: 'BOOK SHOP' },
    { value: '1385', label: 'BOOK SHOP DEALER' },
    { value: '0219', label: 'BOOK STORE PROP' },
    { value: '0221', label: 'BOOK SUPPLIER' },
    { value: '1386', label: 'BOOK TRADER' },
    { value: '0223', label: 'BOUTIQUE' },
    { value: '0224', label: 'BRANCH ASSISTANT MANAGER' },
    { value: '0225', label: 'BRANCH COORDINATOR' },
    { value: '0227', label: 'BRANCH MANAGER' },
    { value: '0226', label: 'BRANCH MARKETING' },
    { value: '0228', label: 'BRANCH OPERATION' },
    { value: '1387', label: 'BRANCH OPERATION TEAM MANAGER' },
    { value: '0229', label: 'BRANCH SUPERVISOR' },
    { value: '0230', label: 'BREAD SELLER' },
    { value: '0231', label: 'BREEDER' },
    { value: '0207', label: 'BRIDAL STUDIO' },
    { value: '0233', label: 'BROKER' },
    { value: '0234', label: 'BUDGET ANALYST' },
    { value: '0235', label: 'BUILDING CONTRACTOR' },
    { value: '0236', label: 'BUILDING EXECUTIVE' },
    { value: '0237', label: 'BUILDING MAINTAINANCE' },
    { value: '1388', label: 'BUILDING MANAGEMENT' },
    { value: '1808', label: 'BUILDING MANAGER' },
    { value: '0238', label: 'BUILDING MATERIALS' },
    { value: '1389', label: 'BUILDING RENOVATION' },
    { value: '0239', label: 'BUILDING SUPERVISOR' },
    { value: '0240', label: 'BULLDOZER DRIVER' },
    { value: '0241', label: 'BUS CONDUCTOR' },
    { value: '0243', label: 'BUS DRIVER' },
    { value: '0188', label: 'BUS FACTORY OWNER' },
    { value: '1390', label: 'BUS INSPECTOR' },
    { value: '1391', label: 'BUS OPERATOR' },
    { value: '0244', label: 'BUS PROPRIETOR' },
    { value: '0242', label: 'BUS SUPERVISOR' },
    { value: '0245', label: 'BUS TICKET SELLER' },
    { value: '1377', label: 'BUS WORKERS' },
    { value: '0196', label: 'BUSINESS' },
    { value: '0246', label: 'BUSINESS ACCOUNTS EXECUTIVE' },
    { value: '0247', label: 'BUSINESS ANALYST' },
    { value: '0248', label: 'BUSINESS DEV. CONSULTANT' },
    { value: '0249', label: 'BUSINESS DEVELOPMENT DIRECTOR' },
    { value: '0250', label: 'BUSINESS DEVELOPMENT EXECUTIVE' },
    { value: '0251', label: 'BUSINESS DEVELOPMENT MANAGER' },
    { value: '0252', label: 'BUSINESS DIVISION MANAGER' },
    { value: '0253', label: 'BUSINESS EXECUTIVE' },
    { value: '0254', label: 'BUSINESS FINANCIAL EXECUTIVE' },
    { value: '0255', label: 'BUSINESS MANAGER' },
    { value: '0256', label: 'BUSINESS PARTNER' },
    { value: '1392', label: 'BUSINESS PLANNING EXECUTIVE' },
    { value: '0257', label: 'BUSINESSMAN' },
    { value: '0258', label: 'BUSINESSWOMAN' },
    { value: '0259', label: 'BUTCHER' },
    { value: '1014', label: 'BUTCHER' },
    { value: '0260', label: 'BUYER' },
    { value: '0261', label: 'CABIN ASSISTANT' },
    { value: '0262', label: 'CABIN CREW' },
    { value: '0263', label: 'CABLE & ENGINEERING FACTORY' },
    { value: '0264', label: 'CABLE CONTRACTOR' },
    { value: '0266', label: 'CAFE OWNER' },
    { value: '1394', label: 'CAKE HOUSE OPERATOR' },
    { value: '0267', label: 'CAKE HOUSE OWNER' },
    { value: '1393', label: 'CAKE SELLER' },
    { value: '0269', label: 'CALL CENTRE EXECUTIVE' },
    { value: '0270', label: 'CAMERAMAN' },
    { value: '0272', label: 'CANDIES SUPPLIER' },
    { value: '0274', label: 'CANOPY' },
    { value: '0276', label: 'CANTEEN' },
    { value: '0277', label: 'CANTEEN ASSISTANT' },
    { value: '1395', label: 'CANTEEN CATERER' },
    { value: '0278', label: 'CANTEEN OPERATOR' },
    { value: '1396', label: 'CANTEEN OWNER' },
    { value: '1397', label: 'CANTEEN SUB-CON' },
    { value: '0279', label: 'CAPTAIN' },
    { value: '1398', label: 'CAPTAIN FERRY' },
    { value: '0280', label: 'CAR ACCESORIES' },
    { value: '1399', label: 'CAR ACCESSORY SHOP OWNER' },
    { value: '1400', label: 'CAR AUTO PARTS DEALER' },
    { value: '0281', label: 'CAR DEALER' },
    { value: '0282', label: 'CAR CARE SERVICE CENTRE' },
    { value: '0283', label: 'CAR JOCKEY' },
    { value: '0284', label: 'CAR MECHANIC' },
    { value: '1401', label: 'CAR PAINT DEALER' },
    { value: '0285', label: 'CAR RENTAL' },
    { value: '1402', label: 'CAR SALES MARKETING' },
    { value: '0286', label: 'CAR SALESMAN' },
    { value: '0287', label: 'CAR SPRAYER' },
    { value: '0288', label: 'CAR TECHNICIAN' },
    { value: '0289', label: 'CARDIOLOGIST' },
    { value: '1403', label: 'CARETAKER' },
    { value: '1404', label: 'CARPENTARY WORKS' },
    { value: '0292', label: 'CARPENTER' },
    { value: '0293', label: 'CARPET DEALER' },
    { value: '1405', label: 'CARPET LAYER' },
    { value: '0294', label: 'CASHIER' },
    { value: '0295', label: 'CASINO TABLE CONDUCTOR' },
    { value: '0296', label: 'CASTING DEBURRING' },
    { value: '1406', label: 'CATERER' },
    { value: '0298', label: 'CATERING' },
    { value: '0299', label: 'CATERING EQUIPMENT RENTAL' },
    { value: '0300', label: 'CATERING SUPERVISOR' },
    { value: '0307', label: 'CHAIRMAN' },
    { value: '0308', label: 'CHAIRMAN PERSONAL ASSISTANT' },
    { value: '0309', label: 'CHAMBER MAID' },
    { value: '0275', label: 'CHANCELLOR UNIVERSITY' },
    { value: '0310', label: 'CHARGEMAN / CHARGE HAND' },
    { value: '0312', label: 'CHARITABLE ORGANISATION' },
    { value: '0311', label: 'CHARITY / WELFARE SOCIETY' },
    { value: '0313', label: 'CHARTERED ACCOUNTANT' },
    { value: '0314', label: 'CHARTERED SECRETARY' },
    { value: '0315', label: 'CHAUFFEUR' },
    { value: '0316', label: 'CHEF' },
    { value: '0317', label: 'CHEMICAL ENGINEER' },
    { value: '0318', label: 'CHEMICAL FACTORY' },
    { value: '1407', label: 'CHEMICAL INDUSTRY' },
    { value: '0319', label: 'CHEMICAL SHOP OWNER' },
    { value: '0320', label: 'CHEMICAL SUPPLIER' },
    { value: '0321', label: 'CHEMICAL TECHNICIAN' },
    { value: '0322', label: 'CHEMICAL TECHNOLOGIST' },
    { value: '0323', label: 'CHEMICAL TRADING' },
    { value: '0324', label: 'CHEMICALS' },
    { value: '1408', label: 'CHEMIST' },
    { value: '0325', label: 'CHEMISTRY' },
    { value: '1409', label: 'CHICKEN RICE OPERATOR' },
    { value: '0326', label: 'CHICKEN RICE SELLER' },
    { value: '0327', label: 'CHIEF' },
    { value: '0328', label: 'CHIEF ACCOUNTANT' },
    { value: '0329', label: 'CHIEF ANALYST' },
    { value: '0330', label: 'CHIEF ASSISTANT TREASURER' },
    { value: '0331', label: 'CHIEF BEAUTY THERAPIST' },
    { value: '0332', label: 'CHIEF CASHIER' },
    { value: '0333', label: 'CHIEF CLERK' },
    { value: '0336', label: 'CHIEF CO-ORDINATOR' },
    { value: '1797', label: 'CHIEF COMMERCIAL OFFICER' },
    { value: '0334', label: 'CHIEF CONDUCTOR' },
    { value: '0335', label: 'CHIEF COOK' },
    { value: '0337', label: 'CHIEF ENGINEER / CONTROLLER' },
    { value: '1412', label: 'CHIEF EXECUTIVE OFFICER' },
    { value: '0339', label: 'CHIEF FINANCIAL OFFICER' },
    { value: '0340', label: 'CHIEF FOREMAN' },
    { value: '0341', label: 'CHIEF INSPECTOR' },
    { value: '1414', label: 'CHIEF MARKETING OFFICER' },
    { value: '0696', label: 'CHIEF MINISTER' },
    { value: '0343', label: 'CHIEF OPERATION OFFICER' },
    { value: '1413', label: 'CHIEF POLICE INSPECTOR' },
    { value: '0344', label: 'CHIEF REPORTER' },
    { value: '1415', label: 'CHIEF REPRESENTATIVE' },
    { value: '0345', label: 'CHIEF REPRESENTATIVE OFFICER' },
    { value: '0346', label: 'CHIEF STEWARD' },
    { value: '0347', label: 'CHIEF STOREKEEPER' },
    { value: '0348', label: 'CHIEF TECHNICIAN' },
    { value: '1691', label: 'CHILDCARE PRINCIPAL' },
    { value: '0353', label: 'CHINESE MEDICAL / PHYSICIAN' },
    { value: '0351', label: 'CHINESE MEDICAL SUPPLIES' },
    { value: '0352', label: 'CHINESE MEDICINE SHOP' },
    { value: '0354', label: 'CHURCH' },
    { value: '0355', label: 'CHURCH ORGANISATION' },
    { value: '1418', label: 'CHURCH PASTOR' },
    { value: '0356', label: 'CHURCH WORKER' },
    { value: '0357', label: 'CIGARATTE DEALER' },
    { value: '1420', label: 'CIVIL & BUILDING CONTRACTOR' },
    { value: '0359', label: 'CIVIL CONTRACTOR' },
    { value: '0360', label: 'CIVIL DEFENCE' },
    { value: '1421', label: 'CIVIL ENGINEER & CONSTRUCTION' },
    { value: '0361', label: 'CIVIL ENGINEER & CONTRACTOR' },
    { value: '1422', label: 'CIVIL ENGINEER & CONTRACTOR' },
    { value: '0362', label: 'CIVIL ENGINEERING & CONST.' },
    { value: '0363', label: 'CIVIL ENGINEERING WORKS' },
    { value: '0364', label: 'CIVIL MANAGER' },
    { value: '0365', label: 'CIVIL SERVANT' },
    { value: '0366', label: 'CLAIMS ASSISTANT' },
    { value: '1424', label: 'CLAIMS EXECUTIVE' },
    { value: '0368', label: 'CLEANER' },
    { value: '1425', label: 'CLEANING SERVICES' },
    { value: '1426', label: 'CLEANING SUPERVISOR' },
    { value: '0369', label: 'CLERICAL ASSISTANT' },
    { value: 'M013', label: 'CLERICAL/ADMINISTRATOR' },
    { value: '0372', label: 'CLERK' },
    { value: '0373', label: 'CLIENT MANAGER' },
    { value: '1428', label: 'CLIENT SERVICE DIRECTOR' },
    { value: '0374', label: 'CLINIC' },
    { value: '0375', label: 'CLINIC / NURSE / NURSE TUTOR' },
    { value: '1429', label: 'CLINIC ASSISTANT' },
    { value: '0376', label: 'CLINIC SUPERVISOR' },
    { value: '0377', label: 'CLOTHES MERCHANT' },
    { value: '1431', label: 'CLOTHING WHOLESALER' },
    { value: '0378', label: 'CLUB' },
    { value: '0379', label: 'CLUB MANAGER' },
    { value: '0429', label: 'CO-ORDINATOR' },
    { value: '0430', label: 'CO-ORDINATOR MANAGER/MARKETING' },
    { value: '0382', label: 'COACH' },
    { value: '1432', label: 'COACH DRIVER' },
    { value: '0383', label: 'COACH MANAGER' },
    { value: '0384', label: 'COATING ADVISOR' },
    { value: '0385', label: 'COBBLER' },
    { value: '0386', label: 'COFEE SHOP' },
    { value: '1433', label: 'COFFEE AGENCY' },
    { value: '1434', label: 'COFFEE DEALER' },
    { value: '0387', label: 'COFFEE SHOP ASSTSSTANT' },
    { value: '1435', label: 'COFFEE SHOP OPERATOR' },
    { value: '0388', label: 'COFFEE SHOP OWNER/PROPRIETOR' },
    { value: '1436', label: 'COFFEE SHOP PROPRIETOR' },
    { value: '1798', label: 'COFFIN SHOP' },
    { value: '0389', label: 'COLD STORAGE' },
    { value: '0390', label: 'COLLECTOR / COLLECTION OFFICER' },
    { value: '0391', label: 'COLLEGE' },
    { value: '1745', label: 'COLLEGE LECTURER' },
    { value: '0392', label: 'COLLEGE STUDENT' },
    { value: '0393', label: 'COMMANDER ARMY' },
    { value: '1475', label: 'COMMISSION SECURITIES' },
    { value: '0394', label: 'COMMODITIES BROKER' },
    { value: '0395', label: 'COMMUNICATION & MEDIA' },
    { value: '0396', label: 'COMMUNICATION CENTRE' },
    { value: '0397', label: 'COMMUNICATION MANAGER' },
    { value: '0398', label: 'COMPANY ASSISTANT' },
    { value: '1438', label: 'COMPANY CHAIRMAN' },
    { value: '0381', label: 'COMPANY CO-ORDINATOR' },
    { value: '0380', label: 'COMPANY DIRECTOR' },
    { value: '1439', label: 'COMPANY DRIVER' },
    { value: '0399', label: 'COMPANY PARTNER' },
    { value: '0400', label: 'COMPANY SECRETARY' },
    { value: '0401', label: 'COMPANY SECRETARY ACCOUNTANT' },
    { value: '0402', label: 'COMPLIANT ACCESSOR' },
    { value: '0403', label: 'COMPOSER' },
    { value: '0271', label: 'COMPUTER ADVISOR / TRAINER' },
    { value: '0405', label: 'COMPUTER ANALYST' },
    { value: '0406', label: 'COMPUTER CONSULTANT / ENGINEER' },
    { value: '0407', label: 'COMPUTER DEALER' },
    { value: 'M014', label: 'COMPUTER ENGINEER/TECHNICIAN' },
    { value: '1442', label: 'COMPUTER IT' },
    { value: '0408', label: 'COMPUTER LECTURER' },
    { value: '0409', label: 'COMPUTER OPERATOR' },
    { value: '1443', label: 'COMPUTER PROGRAMMER' },
    { value: '1444', label: 'COMPUTER REPAIRER' },
    { value: '1445', label: 'COMPUTER SALES & SERVICE' },
    { value: '0404', label: 'COMPUTER SPECIALIST' },
    { value: '0410', label: 'CONCIERGE' },
    { value: '0701', label: 'CONSORTIUM' },
    { value: '0411', label: 'CONSTABLE' },
    { value: '0412', label: 'CONSTRUCTION COMPANY' },
    { value: '0413', label: 'CONSTRUCTION CONTRACTOR' },
    { value: '0414', label: 'CONSTRUCTION DIRECTOR/ MANAGER' },
    { value: '1692', label: 'CONSTRUCTION ENGINEER' },
    { value: '0415', label: 'CONSTRUCTION SUPERVISOR' },
    { value: 'M015', label: 'CONSTRUCTION SUPERVISOR/WORKER' },
    { value: '0416', label: 'CONSTRUCTION WORKER' },
    { value: '1341', label: 'CONSTRUCTION WORKS' },
    { value: '0417', label: 'CONSULATE' },
    { value: '0418', label: 'CONSULTANT' },
    { value: '0419', label: 'CONSULTANT ENGINEER / MANAGER' },
    { value: '0420', label: 'CONSULTANT GEOPHYSICIST' },
    { value: '0421', label: 'CONSUMER PRODUCT' },
    { value: '0422', label: 'CONTRACT MANAGER / OFFICER' },
    { value: '0423', label: 'CONTRACT WORKS' },
    { value: '0424', label: 'CONTRACTOR' },
    { value: '1227', label: 'CONTRACTOR' },
    { value: 'M016', label: 'CONTRACTOR/SUB-CONTRACTOR' },
    { value: '0425', label: 'CONTROL SUPERVISOR' },
    { value: '0426', label: 'CONTROLLER' },
    { value: '0427', label: 'CONVEYANCING ASSISTANT / CLERK' },
    { value: '0428', label: 'COOK / COOK ASSISTANT' },
    { value: '0265', label: 'COORDINATOR' },
    { value: '0431', label: 'COPYWRITER' },
    { value: '0432', label: 'CORPORATE DEALER / EXECUTIVE' },
    { value: '0172', label: 'CORPORATE SECURITY DIVISION' },
    { value: '1792', label: 'CORPORATE WORKER' },
    { value: '0433', label: 'COUNSELOR' },
    { value: '1419', label: 'COURIER EXECUTIVE' },
    { value: '0358', label: 'COURIER SERVICES' },
    { value: '1668', label: 'CRAFT TRAINER' },
    { value: '0434', label: 'CRAFTMAN' },
    { value: '0435', label: 'CRANE DRIVER / OPERATOR' },
    { value: '0436', label: 'CRANE RENTAL/ SERVICES / WORK' },
    { value: '0437', label: 'CREATIVE DIRECTOR' },
    { value: '0439', label: 'CREDIT ANALYST' },
    { value: '0442', label: 'CREDIT CONTROL EXEC / OFFICER' },
    { value: '0440', label: 'CREDIT CONTROL MANAGER' },
    { value: '0441', label: 'CREDIT CONTROL SUPERVISOR' },
    { value: '0438', label: 'CREDIT CONTROLLER' },
    { value: '0443', label: 'CROUPIER' },
    { value: '0444', label: 'CURATOR' },
    { value: '0445', label: 'CUSTOM / OFFICER' },
    { value: '0446', label: 'CUSTOM ASSISTANT / ENGINEER' },
    { value: '1641', label: 'CUSTOM OFFICER' },
    { value: '0448', label: 'CUSTOMER RELATION OFFICER/REP' },
    { value: '0447', label: 'CUSTOMER RELATIONS / MANAGER' },
    { value: '0452', label: 'CUSTOMER SERVICE' },
    { value: '0801', label: 'MICRO BIOLOGIST' },
    { value: '0803', label: 'MICRO ELECTRONICS MANUFACTURER' },
    { value: '0802', label: 'MICRO MOTOR PLANT MANAGER' },
    { value: '0804', label: 'MIDWIFE' },
    { value: '0805', label: 'MILITARY OFFICER' },
    { value: 'M021', label: 'MILITARY/POLICE/CIVI' },
    { value: '0806', label: 'MINI MARKET PROPRIETOR' },
    { value: '0808', label: 'MINISTER' },
    { value: '0809', label: 'MODEL' },
    { value: '0810', label: 'MONEY CHANGER' },
    { value: '0811', label: 'MORTAGE SALES EXECUTIVE' },
    { value: '0812', label: 'MOSAIC / CONTRACTOR' },
    { value: '0813', label: 'MOSAIC LAYER' },
    { value: '0814', label: 'MOTOR ASSEMBLY' },
    { value: '0815', label: 'MOTOR FRANCHISE DEALER' },
    { value: '0816', label: 'MOTOR MECHANIC / WORKSHOP' },
    { value: '0817', label: 'MOTOR PARTS DEALER/SHOP OWNER' },
    { value: '1714', label: 'MOTOR TRADE' },
    { value: '0818', label: 'MOTORCYCLE PARTS MANUFACTURER' },
    { value: '0819', label: 'MOTORCYCLE REPAIRER' },
    { value: '0820', label: 'MOULD MAKER' },
    { value: '0821', label: 'MULTIMEDIA DESIGNER' },
    { value: '1361', label: 'MUSEUM ATTENDANT' },
    { value: '0822', label: 'MUSIC INSTRUCTOR / TEACHER' },
    { value: '0823', label: 'MUSIC PUBLISHING' },
    { value: '0824', label: 'MUSICAL SHOP' },
    { value: '0825', label: 'MUSICIAN' },
    { value: '0826', label: 'MUZIUM ASSISTANT' },
    { value: '0827', label: 'NAVAL OFFICER' },
    { value: '0828', label: 'NAVY / PILOT / OFFICER' },
    { value: '0829', label: 'NAVY ENGINEER / GOVERMENT' },
    { value: '0830', label: 'NEGOTIATOR' },
    { value: '0831', label: 'NETWORK SUPPORT& COMMUNICATION' },
    { value: '0833', label: 'NEWSPAPER AGENT / DEALER' },
    { value: '0832', label: 'NEWSPAPER DISTRIBUTION' },
    { value: '0834', label: 'NEWSPAPER SUPPLIER / VENDORS' },
    { value: '0835', label: 'NIGHT MARKET TRADER' },
    { value: '0836', label: 'NOODLE MAKER / SUPPLIER' },
    { value: '0837', label: 'NUN' },
    { value: '0838', label: 'NURSE' },
    { value: '0839', label: 'NURSERY / OPERATOR' },
    { value: '0840', label: 'NURSING CENTRE / MANAGER' },
    { value: '0841', label: 'NUTRITIONIST' },
    { value: '1735', label: 'OFF ADM/S.VISORY/MGT PERSONNEL' },
    { value: '0842', label: 'OFFICE BOY / CLERK / DRIVER' },
    { value: '0843', label: 'OFFICE EQUIPMENT MANU/SUPPLIER' },
    { value: '0844', label: 'OFFICE GIRLS / WORKER' },
    { value: '0845', label: 'OFFICER' },
    { value: '0044', label: 'OFFICER' },
    { value: '1516', label: 'OFFICER / JUNIOR EXECUTIVE' },
    { value: '1642', label: 'OFFICER CLERK' },
    { value: '1644', label: 'OFFICER FACTORY' },
    { value: '1649', label: 'OFFICER OF UNITY' },
    { value: '0846', label: 'OFFSHORE / OIL & GAS COMPANY' },
    { value: '0847', label: 'OIL PALM PLANTATION' },
    { value: '0848', label: 'OLEOCHEMICAL PLANT / FACTORY' },
    { value: '0849', label: 'OPERATION ADMIN / ASSISTANT' },
    { value: '0850', label: 'OPERATION ADVISOR / EXECUTIVE' },
    { value: '0851', label: 'OPERATION CLERK / LOGISTIC' },
    { value: '0852', label: 'OPERATION MANAGER / OFFICER' },
    { value: '0853', label: 'OPERATION SERVICE / STAFF' },
    { value: '0854', label: 'OPERATION SUPERVISOR / EXEC' },
    { value: '0855', label: 'OPERATION TECHINICIAN' },
    { value: '0856', label: 'OPERATOR' },
    { value: '1716', label: 'OPERATOR' },
    { value: '0857', label: 'OPTICAL / OPTICIAN' },
    { value: '0858', label: 'OPTICAL HOUSE / SHOP ASSISTANT' },
    { value: '0859', label: 'ORTHOPAEDICS SPECIALIST' },
    { value: '0860', label: 'OTHERS' },
    { value: '0861', label: 'OUTBOUND MANAGER' },
    { value: '0862', label: 'OUTLET CHEF/MANAGER/SUPERVISOR' },
    { value: '0863', label: 'OWN BUSINESS' },
    { value: '0864', label: 'PACKAGING / PACKER / PACKING' },
    { value: '0865', label: 'PAINT SPRAYER / PAINTER' },
    { value: '0866', label: 'PAINTING CONTRACTOR' },
    { value: '0867', label: 'PAINTS MANUFACTURER' },
    { value: '0868', label: 'PALM OIL DEALER / OIL MILL' },
    { value: '0869', label: 'PANEL BEATER' },
    { value: '0870', label: 'PANEL PRINTING FACTORY' },
    { value: '0872', label: 'PAPER PRODUCTS IMPORTER' },
    { value: '0871', label: 'PAPER PRODUCTS MANUFACTURER' },
    { value: '0873', label: 'PAPER PRODUCTS WHOLESELLER' },
    { value: '0874', label: 'PARKING ATTENDANT / OPERATOR' },
    { value: '0875', label: 'PARKING CASHIER' },
    { value: '0195', label: 'PARLIAMENT HERALD' },
    { value: '0876', label: 'PARTNER / PARTNERSHIP' },
    { value: '0877', label: 'PASAR MALAM HAWKER / OPERATOR' },
    { value: '0878', label: 'PASTRY MAKER' },
    { value: '1717', label: 'PAWN SHOP' },
    { value: '0880', label: 'PAYROLL CLERK' },
    { value: '0879', label: 'PAYROLL EXECUTIVE / OFFICER' },
    { value: '1718', label: 'PEDDLER' },
    { value: '0882', label: 'PEGAWAI TADBIR & DIPLOMATIK' },
    { value: '0890', label: 'PENGHULU' },
    { value: '0893', label: 'PENOLONG PEGAWAI TADBIR' },
    { value: '0896', label: 'PENSIONER' },
    { value: '0899', label: 'PERFORMING ARTIST' },
    { value: '0898', label: 'PERSONAL ADMIN / ASSISTANT' },
    { value: '0901', label: 'PERSONAL DRIVER / OFFICER' },
    { value: '0902', label: 'PERSONAL FINANCIAL PLANNER' },
    { value: '0903', label: 'PERSONNEL & ADMIN EXECUTIVE' },
    { value: '0904', label: 'PERSONNEL & ADMIN MANAGER' },
    { value: '0905', label: 'PERSONNEL & ADMIN OFFICER' },
    { value: '0906', label: 'PERSONNEL ASSISTANT/EXECUTIVE' },
    { value: '0907', label: 'PERSONNEL MANAGER' },
    { value: '1719', label: 'PERSONNEL OFFICER' },
    { value: '0908', label: 'PEST CONTROL' },
    { value: '0909', label: 'PETITION WRITER' },
    { value: '0910', label: 'PETROL STATION DEALER / OWNER' },
    { value: '0911', label: 'PETROL STATION OPERATOR' },
    { value: '0912', label: 'PETROLEUM ENGINEER' },
    { value: '1720', label: 'PETROLEUM INDUSTRY' },
    { value: '0913', label: 'PETRONAS OIL DEALER / STAFF' },
    { value: '0914', label: 'PETTY TRADER' },
    { value: '0915', label: 'PEWTER' },
    { value: '0916', label: 'PHARMACIST / OFFICER' },
    { value: '0917', label: 'PHARMACY' },
    { value: '0918', label: 'PHARMACY ASSISTANT / OFFICER' },
    { value: '0919', label: 'PHOTO LAB ASSISTANT' },
    { value: '0920', label: 'PHOTO SHOP OWNER / ASSISTANT' },
    { value: '0921', label: 'PHOTO STUDIO' },
    { value: '0922', label: 'PHOTOGRAPHER / PHOTOGRAPHY' },
    { value: '0923', label: 'PHYSICAL INSTRUCTOR' },
    { value: '0924', label: 'PHYSICIAN / PHYSICIAN CLINIC' },
    { value: '0925', label: 'PHYSIOTHERAPIST' },
    { value: '0926', label: 'PIANO TEACHER / INSTRUCTOR' },
    { value: '0927', label: 'PIG FARMING' },
    { value: '0928', label: 'PILING CONTRACTOR/CONSTRUCTION' },
    { value: 'M025', label: 'PILOT' },
    { value: '0929', label: 'PIPE FITTER / MANUFACTURER' },
    { value: '0930', label: 'PIPING' },
    { value: '0931', label: 'PLANNER / PLANNING MANAGER' },
    { value: '1721', label: 'PLANNING TECHNICIAN' },
    { value: '1722', label: 'PLANT DEVELOPMENT CONTRACTOR' },
    { value: '0932', label: 'PLANT MANAGER / OPERATOR' },
    { value: '0933', label: 'PLANT SUPERINTENDENT OPERATION' },
    { value: '0934', label: 'PLANTATION' },
    { value: '0935', label: 'PLANTATION ASSISTANT MANAGER' },
    { value: '0936', label: 'PLANTED FOREST/OIL PALM PLANT' },
    { value: '0937', label: 'PLANTER' },
    { value: '0303', label: 'PLASTER CEILING / CONTRACTOR' },
    { value: '0938', label: 'PLASTIC & METAL RECYCLE' },
    { value: '0939', label: 'PLASTIC MANUFACTURER' },
    { value: '0940', label: 'PLUMBER / PLUMBING CONTRACTOR' },
    { value: '0941', label: 'POLICE' },
    { value: '1163', label: 'POLICE /OFFICER/SENIOR OFFICER' },
    { value: '0895', label: 'POLICE ASST. SUPERINTENDENT' },
    { value: '0942', label: 'POLICE CHIEF' },
    { value: '0943', label: 'POLICE CONSTABLE / DECTECTIVE' },
    { value: '1734', label: 'POLICE DEPUTY SUPERINTENDENT' },
    { value: '1788', label: 'POLICE HELPER' },
    { value: '0944', label: 'POLICE INSPECTOR / OFFICER' },
    { value: '0945', label: 'POLICEMAN / POLICEWOMAN' },
    { value: '0946', label: 'POLISHER' },
    { value: '0947', label: 'POLITICIAN' },
    { value: '1202', label: 'POLITICS SECRETARY' },
    { value: '0948', label: 'PORK SELLER' },
    { value: '1723', label: 'PORT ASSISTANT' },
    { value: '0949', label: 'POSTMAN' },
    { value: '0950', label: 'POTTERY MANUFACTURER' },
    { value: '0951', label: 'POULTRY DEALERS/SUPPLIER/FARM' },
    { value: '1410', label: 'POULTRY SELLER' },
    { value: '1411', label: 'POULTRY WHOLESALER' },
    { value: '0952', label: 'PR EXECUTIVE / PR MANAGERESS' },
    { value: '0953', label: 'PRECISION' },
    { value: '0954', label: 'PRESIDENT' },
    { value: '0955', label: 'PRESS SECRETARY PRIME MINISTER' },
    { value: '0956', label: 'PRIEST' },
    { value: '0957', label: 'PRINCIPAL' },
    { value: '0958', label: 'PRINCIPAL ASSISTANT DIRECTOR' },
    { value: '0959', label: 'PRINCIPAL CONSULTANT / OFFICER' },
    { value: '0961', label: 'PRINTER / PRINTING' },
    { value: '1724', label: 'PRINTING & PACKAGING' },
    { value: '0962', label: 'PRINTING ASSISTANT / OPERATOR' },
    { value: '0963', label: 'PRINTING PRESS / WORKS' },
    { value: '1671', label: 'PRISON AUTHORITIES' },
    { value: '0964', label: 'PRISON OFFICER / WARDEN' },
    { value: '1477', label: 'PRIVATE SECTOR' },
    { value: '0965', label: 'PRIVATE SERVANT' },
    { value: '0966', label: 'PRIVATE TUTOR' },
    { value: '0967', label: 'PROCESS CONTROLLER' },
    { value: '0973', label: 'PROCUCTION ASSISTANT PRINTING' },
    { value: '0968', label: 'PROCUREMENT ANALYST' },
    { value: '0969', label: 'PRODUCER' },
    { value: '0970', label: 'PRODUCT CONSULTANT/CONTROLLER' },
    { value: '0971', label: 'PRODUCT PLANNER / SPECIALIST' },
    { value: '0972', label: 'PRODUCTION ADVISOR / ARTISAN' },
    { value: '0974', label: 'PRODUCTION CONTROLLER/ENGINEER' },
    { value: '0975', label: 'PRODUCTION ENGINEERING MANAGER' },
    { value: '0976', label: 'PRODUCTION EXECUTIVE' },
    { value: '0977', label: 'PRODUCTION FACILITY / FACTORY' },
    { value: '0719', label: 'PRODUCTION MANAGER' },
    { value: '0978', label: 'PRODUCTION OPERATOR / PLANNING' },
    { value: '0979', label: 'PRODUCTION STAFF / SUPERVISOR' },
    { value: '0980', label: 'PRODUCTION TRAINER / WORKER' },
    { value: '1725', label: 'PRODUCTS DEVELOPMENT MANAGER' },
    { value: '0983', label: 'PROFESSIONAL' },
    { value: 'M026', label: 'PROFESSIONAL' },
    { value: '0981', label: 'PROFESSIONAL BADMINTON PLAYER' },
    { value: '1736', label: 'PROFESSIONAL DRIVER / DRIVER' },
    { value: '0982', label: 'PROFESSOR' },
    { value: '0984', label: 'PROGRAM CO-ORDINATOR EXECUTIVE' },
    { value: '0985', label: 'PROGRAMMER' },
    { value: '0986', label: 'PROJECT & TRADE CONSULTANT' },
    { value: '0987', label: 'PROJECT ASSISTANT / CONSULTANT' },
    { value: '0988', label: 'PROJECT CO-ORDINATION MANAGER' },
    { value: '0989', label: 'PROJECT CO-ORDINATOR' },
    { value: '0990', label: 'PROJECT DIRECTOR / ENGINEER' },
    { value: '0991', label: 'PROJECT EXECUTIVE / LEADER' },
    { value: '0960', label: 'PROJECT MANAGER' },
    { value: '0992', label: 'PROJECT MANAGER / SECRETARY' },
    { value: '0993', label: 'PROMOTER' },
    { value: '0994', label: 'PROMOTION & LOYALTY SPECIALIST' },
    { value: '0995', label: 'PROMOTION MANAGER' },
    { value: '0996', label: 'PROPERTIES MANAGEMENT' },
    { value: '1799', label: 'PROPERTY AGENT' },
    { value: '0997', label: 'PROPERTY AGENT / BROKER' },
    { value: '0998', label: 'PROPERTY CONSULTANT / OWNER' },
    { value: '0999', label: 'PROPERTY DEVELOPER/MANAGEMENT' },
    { value: '1000', label: 'PROPERTY MANAGER /NEGOTIATOR' },
    { value: '1001', label: 'PROPRIETOR' },
    { value: '1002', label: 'PROVISON SHOP' },
    { value: '1003', label: 'PUB OPERATOR' },
    { value: '1004', label: 'PUBLIC ACCOUNTANT' },
    { value: '1005', label: 'PUBLIC AFFAIRS / RELATIONS' },
    { value: '1006', label: 'PUBLIC RELATIONS / EXECUTIVE' },
    { value: '0694', label: 'PUBLIC SURVEY TECHNICIAN' },
    { value: '1007', label: 'PUBLICATION CO-ORDINATOR' },
    { value: '1008', label: 'PUBLISHING' },
    { value: '1009', label: 'PUMP ATTENDANT' },
    { value: '1010', label: 'PURCHASER / PURCHASING ADVISOR' },
    { value: '1011', label: 'PURCHASING ASSISTANT MANAGER' },
    { value: '1012', label: 'PURCHASING CLERK / EXECUTIVE' },
    { value: '1013', label: 'PURCHASING MANAGER / OFFICER' },
    { value: '1017', label: 'QA DEPT / ENGINEER / EXECUTIVE' },
    { value: '1015', label: 'QA INSPECTOR / SUPERVISOR' },
    { value: '1016', label: 'QC INSPECTOR /SENIOR EXECUTIVE' },
    { value: '1019', label: 'QUALITY ASSURANCE MANAGER' },
    { value: '1020', label: 'QUALITY CHECKING / CONTROLLER' },
    { value: '1021', label: 'QUALITY CONTROL OFFICER' },
    { value: '1022', label: 'QUALITY ENGINEER / INSPECTOR' },
    { value: '1023', label: 'QUALITY SURVEYOR' },
    { value: '0900', label: 'QUEEN' },
    { value: '1024', label: 'RADIOGRAPHER / RADIOLOGIST' },
    { value: '1025', label: 'RAMP SERVICE' },
    { value: '1026', label: 'REAL ESTATE' },
    { value: '1027', label: 'REAL ESTATE AGENT / MANAGER' },
    { value: '1028', label: 'REAL ESTATE NEGOTIATOR' },
    { value: '1029', label: 'RECEPTIONIST' },
    { value: '1030', label: 'REFLEXOLOGIST' },
    { value: '1031', label: 'REGIONAL DIRECTOR / EXECUTIVE' },
    { value: '1032', label: 'REGIONAL FINANCE DIRECTOR' },
    { value: '1033', label: 'REGIONAL FINANCIAL CONTROLLER' },
    { value: '1034', label: 'REGIONAL MANAGER / SALES' },
    { value: '1035', label: 'REGISTRATION CLERK' },
    { value: '1036', label: 'RELIGIOUS ASSOCIATION' },
    { value: '1037', label: 'RELIGIOUS ORGANISATION' },
    { value: '1038', label: 'REMISIER' },
    { value: '1039', label: 'RENOVATION / RENOVATION WORKS' },
    { value: 'M027', label: 'RENOVATION CONTRACTOR' },
    { value: '1040', label: 'RENOVATION CONTRACTOR / WORKER' },
    { value: '1041', label: 'RENTAL BUSINESS / SERVICES' },
    { value: '1042', label: 'REPORTER' },
    { value: '1044', label: 'RESEARCH' },
    { value: '1043', label: 'RESEARCH ANALYST / ASSISTANT' },
    { value: '1664', label: 'RESEARCH ASSISTANT' },
    { value: '1045', label: 'RESEARCH EXECUTIVE' },
    { value: '1646', label: 'RESEARCH OFFICER' },
    { value: '1046', label: 'RESEARCHER' },
    { value: '1047', label: 'RESERVATION MANAGER / OFFICER' },
    { value: '1672', label: 'RESIDENTAL SUPERVISOR' },
    { value: '1050', label: 'RESTAURANT / RESTAURANT OWNER' },
    { value: '1048', label: 'RESTAURANT CAPTAIN / OPERATOR' },
    { value: '1049', label: 'RESTAURANT DIRECTOR / MANAGER' },
    { value: '1051', label: 'RESTAURANT SUPERVISOR / WORKER' },
    { value: '1052', label: 'RETAIL EXECUTIVE / MANAGER' },
    { value: '1053', label: 'RETAIL FINANCIAL PLANNER' },
    { value: '1054', label: 'RETAIL FINANCIAL SERVICES' },
    { value: '1055', label: 'RETAIL MARKETING' },
    { value: '1056', label: 'RETAIL SHOP MANAGER / TRADER' },
    { value: '1057', label: 'RETAILER' },
    { value: '1058', label: 'RETIRED' },
    { value: '1059', label: 'RETIRED BANKER / POLICE' },
    { value: '1060', label: 'RETIRED HEADMASTER / TEACHER' },
    { value: 'M028', label: 'RETIREE' },
    { value: '1061', label: 'RIDER' },
    { value: '1062', label: 'RIGGER' },
    { value: '1063', label: 'RISK & CREDIT MANAGER' },
    { value: '1064', label: 'RISK MANAGER / RISK SURVEYOR' },
    { value: '1065', label: 'ROAD MARKER' },
    { value: '1809', label: 'ROYALTY' },
    { value: '1067', label: 'RUBBER ESTATE OWNER / DEALER' },
    { value: '1068', label: 'RUBBER TAPPER / PRODUCT' },
    { value: '1069', label: 'RUNNER' },
    { value: '1070', label: 'SAFEGUARD' },
    { value: '1071', label: 'SAFETY INSPECTOR / OFFICER' },
    { value: '1072', label: 'SAILOR' },
    { value: '1727', label: 'SALES / SERVICE PERSONNEL' },
    { value: '1517', label: 'SALES & MARKETING' },
    { value: '1074', label: 'SALES & MARKETING ENGINEER' },
    { value: '1075', label: 'SALES & MARKETING MANAGER' },
    { value: '1073', label: 'SALES & SALE PROPRIETOR' },
    { value: '1076', label: 'SALES & SITE SUPERVISOR /ADMIN' },
    { value: '1077', label: 'SALES ADMINISTRATOR / ADVISOR' },
    { value: '1078', label: 'SALES ADVERTISING / ASSISTANT' },
    { value: '1079', label: 'SALES CLERK / CONSULTANT' },
    { value: '1080', label: 'SALES CO-ORDIANTOR / DIRECTOR' },
    { value: '1787', label: 'SALES DIRECTOR' },
    { value: '1081', label: 'SALES ENGINEER / EXECUTIVE' },
    { value: '0026', label: 'SALES MANAGER' },
    { value: '1082', label: 'SALES MANAGER / MARKETING' },
    { value: '1083', label: 'SALES MARKETING / OFFICER' },
    { value: '1726', label: 'SALES PURCHASE CO-ORDINATOR' },
    { value: '1084', label: 'SALES REPRESENTATIVE /PROMOTER' },
    { value: '1085', label: 'SALES SPECIALIST / SUPERVISOR' },
    { value: 'M029', label: 'SALES/MARKETING/SERVICE' },
    { value: '1086', label: 'SALESGIRL / SALESMAN' },
    { value: '1087', label: 'SALOON OWNER' },
    { value: '1088', label: 'SARJAN / DETEKTIF / MEJAR' },
    { value: '1089', label: 'SAWMILL OPERATOR / WORKER' },
    { value: '1090', label: 'SCALER' },
    { value: '1091', label: 'SCHOOL BUS DRIVER / OPERATOR' },
    { value: '1092', label: 'SCHOOL CANTEEN' },
    { value: '1093', label: 'SCHOOL MASTER / SCHOOL TEACHER' },
    { value: '1652', label: 'SCIENCE OFFICER' },
    { value: '0037', label: 'SCIENTIST' },
    { value: '1094', label: 'SCIENTIST/MEDICAL TECHNOLOGIST' },
    { value: '1095', label: 'SCRAP METAL DEALER' },
    { value: '1096', label: 'SEA FOOD SUPPLIER / DEALER' },
    { value: '1097', label: 'SEAMSTRESS' },
    { value: '1098', label: 'SECRETARIAL ASSISTANT/CONSULT' },
    { value: '1099', label: 'SECRETARY' },
    { value: '0163', label: 'SECURITY / SECURITIES' },
    { value: '1100', label: 'SECURITY ASSISTANT /CONTROLLER' },
    { value: '1101', label: 'SECURITY GUARD / OFFICER' },
    { value: '1102', label: 'SECURITY MANAGER / OFFICER' },
    { value: '1103', label: 'SECURITY SERVICES / SUPERVISOR' },
    { value: '1104', label: 'SECURITY SYSTEM CONSULTANT' },
    { value: '1105', label: 'SELF EMPLOYED / PROPRIETOR' },
    { value: 'M033', label: 'SELF EMPLOYED/OWN COMPANY' },
    { value: '1106', label: 'SELLING FLOWER' },
    { value: '1107', label: 'SEMICONDUCTOR MANUFACTURING' },
    { value: '1130', label: 'SENIOR / CONTRACTS EXECUTIVE' },
    { value: '1108', label: 'SENIOR ACCOUNT MANAGER' },
    { value: '1109', label: 'SENIOR ACCOUNTANT' },
    { value: '1110', label: 'SENIOR ACCOUNTS ASSISTANT' },
    { value: '1111', label: 'SENIOR ACCOUNTS CLERK' },
    { value: '1112', label: 'SENIOR ACCOUNTS EXECUTIVE' },
    { value: '1113', label: 'SENIOR ACCOUNTS OFFICER' },
    { value: '1114', label: 'SENIOR ADMIN / ADMINISTRATOR' },
    { value: '1115', label: 'SENIOR ADMIN MANAGER' },
    { value: '1116', label: 'SENIOR ADMINISTRATOR ASSISTANT' },
    { value: '1117', label: 'SENIOR ADVISOR / ANALYST' },
    { value: '1118', label: 'SENIOR AGENT / ASSISTANT' },
    { value: '1119', label: 'SENIOR APPLICATION SPECIALIST' },
    { value: '1729', label: 'SENIOR ART DIRECTOR' },
    { value: '1120', label: 'SENIOR ASSISTANT DIRECTOR' },
    { value: '1122', label: 'SENIOR ASSOCIATE' },
    { value: '1121', label: 'SENIOR ASST STUDENT AFFAIR' },
    { value: '1123', label: 'SENIOR AUDIT / EXECUTIVE' },
    { value: '1124', label: 'SENIOR BRANCH MANAGER' },
    { value: '1125', label: 'SENIOR BUSINESS EXECUTIVE' },
    { value: '1126', label: 'SENIOR BUYER' },
    { value: '1127', label: 'SENIOR CARGO ASSISTANT' },
    { value: '1128', label: 'SENIOR CLERK' },
    { value: '1129', label: 'SENIOR CONDUCTOR / CONSULTANT' },
    { value: '1131', label: 'SENIOR CREDIT CONTROL EXEC.' },
    { value: '1132', label: 'SENIOR DESIGNER' },
    { value: '1133', label: 'SENIOR DISTRICT MANAGER' },
    { value: '1134', label: 'SENIOR DRAUGHTSMAN' },
    { value: '1135', label: 'SENIOR ENGINEER / EXECUTIVE' },
    { value: '1172', label: 'SENIOR ESTATE NEGOTIATOR' },
    { value: '1136', label: 'SENIOR EXECUTIVE CLAIMS' },
    { value: '1137', label: 'SENIOR EXECUTIVE OFFICER' },
    { value: '1138', label: 'SENIOR EXECUTIVE SECRETARY' },
    { value: '1139', label: 'SENIOR GENERAL MANAGER' },
    { value: '1140', label: 'SENIOR GROUP MANAGER' },
    { value: '1141', label: 'SENIOR HUMAN RESOURCE MANAGER' },
    { value: '1142', label: 'SENIOR INDUSTRIAL MANAGER' },
    { value: '1143', label: 'SENIOR INSTITUTIONAL DEALER' },
    { value: '1144', label: 'SENIOR IT ENGINEER / MANAGER' },
    { value: '1145', label: 'SENIOR JUDGE' },
    { value: '1146', label: 'SENIOR LECTURER' },
    { value: '1147', label: 'SENIOR LEGAL COUNSEL / MANAGER' },
    { value: '1148', label: 'SENIOR LINE LEADER' },
    { value: '1149', label: 'SENIOR MAINTENANCE SUPERVISOR' },
    { value: '1150', label: 'SENIOR MANAGEMENT CONSULTANT' },
    { value: '1151', label: 'SENIOR MANAGER' },
    { value: '1152', label: 'SENIOR MANAGER TECHNICAL' },
    { value: '1153', label: 'SENIOR MARKETING EXECUTIVE' },
    { value: '1154', label: 'SENIOR MARKETING MANAGER' },
    { value: '1155', label: 'SENIOR MORTGAGE SALES OFFICER' },
    { value: '1156', label: 'SENIOR NEGOTIATOR' },
    { value: '1157', label: 'SENIOR OFFICER' },
    { value: '1158', label: 'SENIOR OPERATION EXECUTIVE' },
    { value: '1159', label: 'SENIOR OPERATION MANAGER' },
    { value: '1160', label: 'SENIOR OPERATOR' },
    { value: '1161', label: 'SENIOR PASTOR' },
    { value: '1162', label: 'SENIOR PERSONNEL EXECUTIVE' },
    { value: '1164', label: 'SENIOR PRODUCTION ENGINEER' },
    { value: '1165', label: 'SENIOR PROGRAMMER' },
    { value: '1167', label: 'SENIOR PROJECT COORDINATOR' },
    { value: '1166', label: 'SENIOR PROJECT ENGINEER' },
    { value: '1168', label: 'SENIOR PROJECT EXECUTIVE' },
    { value: '1169', label: 'SENIOR PROJECT MANAGER' },
    { value: '1170', label: 'SENIOR PROJECT OFFICER' },
    { value: '1171', label: 'SENIOR QUANTITY SURVEYOR' },
    { value: '112', label: 'SENIOR REAL ESTATE NEGOTIATOR' },
    { value: '1173', label: 'SENIOR REMISER' },
    { value: '1174', label: 'SENIOR RESORT MANAGER' },
    { value: '1175', label: 'SENIOR SALES ANALYST' },
    { value: '1176', label: 'SENIOR SALES ASSISTANT' },
    { value: '1177', label: 'SENIOR SALES CONSULTANT' },
    { value: '1178', label: 'SENIOR SALES ENGINEER' },
    { value: '1179', label: 'SENIOR SALES EXECUTIVE' },
    { value: '1180', label: 'SENIOR SECRETARY' },
    { value: '1181', label: 'SENIOR SITES SUPERVISOR' },
    { value: '1182', label: 'SENIOR SOLUTIONS DEVELOPMENT' },
    { value: '1183', label: 'SENIOR SPECIALIST' },
    { value: '1184', label: 'SENIOR STOREHAND' },
    { value: '1185', label: 'SENIOR STOREKEEPER' },
    { value: '1186', label: 'SENIOR STORYBOARD ARTIST' },
    { value: '1187', label: 'SENIOR SUPERVISOR' },
    { value: '1188', label: 'SENIOR SYSTEM ANALYST/ENGINEER' },
    { value: '1189', label: 'SENIOR TECHNICAL ASSISTANT' },
    { value: '1190', label: 'SENIOR TECHNICAL MANAGER' },
    { value: '1191', label: 'SENIOR TECHNICAL OPERATOR' },
    { value: '1192', label: 'SENIOR TECHNICIAN / EXECUTIVE' },
    { value: '1193', label: 'SENIOR VICE PRESIDENT' },
    { value: '1194', label: 'SENIOR WELDING INSPECTOR' },
    { value: '1195', label: 'SERVICE ADVISOR / MANAGER' },
    { value: '1196', label: 'SERVICE CLERK / SERVICEMAN' },
    { value: '1197', label: 'SERVICE COMPANY / MANAGEMENT' },
    { value: '1198', label: 'SERVICE ENGINEER / EXECUTIVE' },
    { value: '1199', label: 'SERVICE REPRESENTATIVE' },
    { value: '1804', label: 'SERVICES SECTOR' },
    { value: '1200', label: 'SESSION COURT JUDGE' },
    { value: '1203', label: 'SETTLER' },
    { value: '1204', label: 'SEWING OPERATOR' },
    { value: '1205', label: 'SHIP CAPTAIN / ASSISTANT' },
    { value: '1206', label: 'SHIPPING & FORWARDING AGENT' },
    { value: '1207', label: 'SHIPPING COMPANY / PLANNER' },
    { value: '1208', label: 'SHIPPING EXECUTIVE / OFFICER' },
    { value: '1209', label: 'SHIPPING MANAGER' },
    { value: '1210', label: 'SHOE MANUFACTURER / MAKER' },
    { value: '1211', label: 'SHOP ASSISTANT / ATTENDANT' },
    { value: '1213', label: 'SHOP MANAGER / SUPERVISOR' },
    { value: '1212', label: 'SHOP PROPRIETOR / SHOP OWNER' },
    { value: '1214', label: 'SHOPKEEPER' },
    { value: '1215', label: 'SIGNBOARD MAKER / PRINTER' },
    { value: '1216', label: 'SILVERSMITH' },
    { value: '1217', label: 'SINGER' },
    { value: '1218', label: 'SITE AGENT / SITE DRIVER' },
    { value: '1219', label: 'SITE ENGINEER / SITE MANAGER' },
    { value: '1220', label: 'SITE REPRESENTATIVE' },
    { value: '1221', label: 'SITE SUPERVISOR / VERIFICATION' },
    { value: '1793', label: 'SKILL WORKER' },
    { value: '1223', label: 'SMALL HOLDER' },
    { value: '1224', label: 'SOCIAL WORKER / DEVELOPMENT' },
    { value: '1225', label: 'SOCIETY' },
    { value: '1226', label: 'SOFTWARE ENGINEER / SPECIALIST' },
    { value: '1228', label: 'SOLE-PROPRIETOR' },
    { value: '1229', label: 'SOLICITOR' },
    { value: '1230', label: 'SOUND SYSTEM COMPANY DIRECTOR' },
    { value: '1231', label: 'SPARE PARTS DEALER' },
    { value: '1232', label: 'SPARE PARTS SHOP' },
    { value: '1233', label: 'SPECIALIST' },
    { value: '1234', label: 'SPECIALIST ENGINEER / SERVICES' },
    { value: '1235', label: 'SPORT SUPERVISOR / OFFICER' },
    { value: '1236', label: 'SPORTS COORDINATOR' },
    { value: '1237', label: 'SPRAY PAINTING WORKS' },
    { value: '1238', label: 'SQUASH PLAYER' },
    { value: '1240', label: 'STAFF ENGINEER' },
    { value: '1241', label: 'STAGER' },
    { value: '1242', label: 'STAINLESS STEEL WORKS' },
    { value: '1243', label: 'STALL HOLDER / STALL OWNER' },
    { value: '1244', label: 'STATION DEALER' },
    { value: '1245', label: 'STATION MANAGER / MASTER' },
    { value: '1446', label: 'STATIONERY / STATIONERY SHOP' },
    { value: '1447', label: 'STATIONERY MANUFACTURER' },
    { value: '1246', label: 'STATIONERY SHOP' },
    { value: '0170', label: 'STATUTORY BODIES' },
    { value: '1247', label: 'STEEL COMPANY' },
    { value: '1448', label: 'STEEL MANUFACTURER' },
    { value: '1449', label: 'STEEL PROCESSING' },
    { value: '1248', label: 'STEEL WORKS' },
    { value: '1450', label: 'STENOGRAPHER' },
    { value: '1451', label: 'STEWARD / STEWARDESS' },
    { value: '1452', label: 'STEWARD SUPERVISOR' },
    { value: '1249', label: 'STIRE CLERK' },
    { value: '1454', label: 'STOCK ARRANGER' },
    { value: '1453', label: 'STOCKIST' },
    { value: '1458', label: 'STORE / SITE CO-ORDINATOR' },
    { value: '1455', label: 'STORE ADMINISTRATION' },
    { value: '1456', label: 'STORE ASSISTANT' },
    { value: '1457', label: 'STORE KEEPER' },
    { value: '1250', label: 'STORE OFFICER' },
    { value: '1459', label: 'STOREHAND' },
    { value: '1251', label: 'STOREMAN' },
    { value: '1460', label: 'STRATEGY MANAGER' },
    { value: 'M031', label: 'STUDENT' },
    { value: '1461', label: 'SUB EDITOR' },
    { value: '1462', label: 'SUB-AIR CONDITIONING' },
    { value: '1252', label: 'SUB-CONSTRUCTION' },
    { value: '1464', label: 'SUB-CONTRACTOR' },
    { value: '1463', label: 'SULTAN' },
    { value: '1465', label: 'SUNDRY' },
    { value: '1467', label: 'SUNDRY GOODS' },
    { value: '1466', label: 'SUNDRY GOODS DEALER' },
    { value: '1254', label: 'SUNDRY GOODS PROPRIETOR' },
    { value: '1468', label: 'SUNDRY MANAGER' },
    { value: '1255', label: 'SUNDRY MERCHANT' },
    { value: '1253', label: 'SUNDRY SHOP' },
    { value: '1470', label: 'SUNDRY SHOP OWNER' },
    { value: '1256', label: 'SUNDRY SHOP PROPRIETOR' },
    { value: '1471', label: 'SUNDRY SUPPLIER' },
    { value: '0891', label: 'SUPERINTENDANT OF CUSTOMS' },
    { value: '1469', label: 'SUPERINTENDENT' },
    { value: '1472', label: 'SUPERMARKET DEPT STORES' },
    { value: '0712', label: 'SUPERVISOR' },
    { value: '0897', label: 'SUPERVISOR' },
    { value: '1257', label: 'SUPERVISOR FURNITURE' },
    { value: '0175', label: 'SUPPLIER' },
    { value: '1473', label: 'SUPPLY & TRADING' },
    { value: '1474', label: 'SUPPORT EXECUTIVE' },
    { value: '1258', label: 'SURGEON' },
    { value: '1710', label: 'SURVEY TECHNICIAN' },
    { value: '1476', label: 'SURVEYOR' },
    { value: '1478', label: 'SWIMMING COACH' },
    { value: '1479', label: 'SWIMMING POOLS CONTRACTOR' },
    { value: '1259', label: 'SYSTEM ADMIN SUPERVISOR' },
    { value: '1481', label: 'SYSTEM ADMINISTRATOR' },
    { value: '1260', label: 'SYSTEM ANALYST' },
    { value: '1482', label: 'SYSTEM CO-ORDINATOR' },
    { value: '1483', label: 'SYSTEM ENGINEER' },
    { value: '1261', label: 'SYSTEM MANAGER' },
    { value: '1484', label: 'SYSTEM SUPPORT' },
    { value: '1485', label: 'TAILOR' },
    { value: '1262', label: 'TAILOR SHOP OWNER' },
    { value: '1486', label: 'TAX ASSISTANT' },
    { value: '1263', label: 'TAX CONSULTANT' },
    { value: '1487', label: 'TAX DIRECTOR' },
    { value: '1264', label: 'TAX MANAGER' },
    { value: '1488', label: 'TAX OFFICER' },
    { value: '1489', label: 'TAXI DRIVER' },
    { value: '1265', label: 'TAXI SERVICES' },
    { value: '1491', label: 'TEA LADY' },
    { value: '1492', label: 'TEA MERCHANT' },
    { value: '1493', label: 'TEACHER / LECTURER' },
    { value: '1494', label: 'TEAM LEADER' },
    { value: '1495', label: 'TECHNICAL' },
    { value: '1267', label: 'TECHNICAL ADVISOR' },
    { value: '1496', label: 'TECHNICAL ANALYST' },
    { value: '1268', label: 'TECHNICAL ASSISTANT' },
    { value: '1498', label: 'TECHNICAL CO-ORDINATOR' },
    { value: '1497', label: 'TECHNICAL CONSULTANT' },
    { value: '1499', label: 'TECHNICAL DIRECTOR' },
    { value: '1270', label: 'TECHNICAL ENGINEER' },
    { value: '1500', label: 'TECHNICAL EXECUTIVE' },
    { value: '1269', label: 'TECHNICAL MANAGER' },
    { value: '1501', label: 'TECHNICAL MANUFACTURING' },
    { value: '1271', label: 'TECHNICAL OFFICER' },
    { value: '1272', label: 'TECHNICAL PROFESSIONAL' },
    { value: '1503', label: 'TECHNICAL PROJECT LEADER' },
    { value: '1273', label: 'TECHNICAL SALE' },
    { value: '1730', label: 'TECHNICAL SPECIALIST' },
    { value: '1504', label: 'TECHNICAL SPORT' },
    { value: '1274', label: 'TECHNICAL SUPPORT' },
    { value: '1505', label: 'TECHNICAL TRAINER' },
    { value: '0032', label: 'TECHNICIAN' },
    { value: '1276', label: 'TECHNICIAN' },
    { value: '1506', label: 'TECHNICIAN SUPERVISOR' },
    { value: '1507', label: 'TECHNOLOGIST' },
    { value: '1509', label: 'TELECOMMUNICATION' },
    { value: '1275', label: 'TELECOMMUNICATION SERVICE' },
    { value: '1510', label: 'TELECOMUNICATION PROJECT' },
    { value: '1519', label: 'TELEMARKETING' },
    { value: '1520', label: 'TELEMARKETING EXECUTIVE' },
    { value: '1521', label: 'TELEPHONIST' },
    { value: '1522', label: 'TELLER' },
    { value: '1523', label: 'TEMPLE ASSISTANT' },
    { value: '1524', label: 'TENTERA LAUT DIRAJA MALAYSIA' },
    { value: '1525', label: 'TERMINAL PRINTER TECH. MANAGER' },
    { value: '1526', label: 'TERRITORY MANAGER' },
    { value: '1527', label: 'TESTING JIGS MANUFACTURER' },
    { value: '1528', label: 'TEXTILE MANUFACTURER' },
    { value: '1278', label: 'TEXTILE MERCHANT' },
    { value: '1529', label: 'TEXTILE SHOP PROPRIETOR' },
    { value: '1610', label: 'THE PEOPLE REPRESENTATIVES' },
    { value: '1530', label: 'THERAPHY CENTRE / THERAPIST' },
    { value: '1279', label: 'THERAPIST' },
    { value: '1542', label: 'TICKETING' },
    { value: '1531', label: 'TICKETING' },
    { value: '1532', label: 'TILE SHOP OWNER' },
    { value: '1280', label: 'TILING WORKS' },
    { value: '1533', label: 'TIMBER' },
    { value: '1534', label: 'TIMBER CONTRACTOR' },
    { value: '1535', label: 'TIMBER GRADER' },
    { value: '1282', label: 'TIMBER LOGGER' },
    { value: '1536', label: 'TIMBER MERCHANT' },
    { value: '1283', label: 'TIMBER SHOP' },
    { value: '1284', label: 'TIMBER TRADING' },
    { value: '1281', label: 'TIMBER WORKS' },
    { value: '1537', label: 'TIMBER YARD OPERATOR' },
    { value: '1538', label: 'TNB' },
    { value: '1287', label: 'TOOL MAKER' },
    { value: '1540', label: 'TOOL PUSHER' },
    { value: '1541', label: 'TOOLING SUPERVISOR' },
    { value: '1543', label: 'TOUR & TRAVEL AGENCY' },
    { value: '1544', label: 'TOUR AGENCY' },
    { value: '1288', label: 'TOUR CO-ORDINATOR' },
    { value: '1545', label: 'TOUR EXECUTIVE' },
    { value: '1546', label: 'TOUR GUIDE' },
    { value: '1291', label: 'TOUR LEADER' },
    { value: '1548', label: 'TOUR MANAGER' },
    { value: '1292', label: 'TOUR OPERATOR' },
    { value: '1549', label: 'TOURIST' },
    { value: '1550', label: 'TOWER ERECTOR' },
    { value: '1551', label: 'TOWING OPERATOR' },
    { value: '1552', label: 'TOWN PLANNER' },
    { value: '1647', label: 'TOWN PLANNING OFFICER' },
    { value: '1553', label: 'TRACTOR DRIVER' },
    { value: '1555', label: 'TRACTOR MARKETING OFFICER' },
    { value: '1294', label: 'TRACTOR OPERATOR' },
    { value: '1554', label: 'TRACTOR OWNER' },
    { value: '1295', label: 'TRACTOR REPAIRER' },
    { value: '0194', label: 'TRADER' },
    { value: '1556', label: 'TRADING' },
    { value: '1296', label: 'TRADING COMPANY' },
    { value: '1557', label: 'TRADING FIRM / PROPERTY' },
    { value: '1558', label: 'TRADING TEXTILE' },
    { value: '1559', label: 'TRAFFIC ASSISTANT' },
    { value: '1560', label: 'TRAFFIC CO-ORDINATOR' },
    { value: '1298', label: 'TRAFFIC CONTROLLER' },
    { value: '1562', label: 'TRAINEE DOCTOR' },
    { value: '1563', label: 'TRAINEE ENGINEER' },
    { value: '1564', label: 'TRAINEE PHARMACIST' },
    { value: '1299', label: 'TRAINER' },
    { value: '1565', label: 'TRAINING CENTRE' },
    { value: '1300', label: 'TRAINING CONSULTANT' },
    { value: '1566', label: 'TRAINING COORDINATION EXEC.' },
    { value: '1567', label: 'TRAINING ENGINEERING' },
    { value: '1568', label: 'TRAINING EXECUTIVE' },
    { value: '1301', label: 'TRAINING MANAGER' },
    { value: '1569', label: 'TRAINING OFFICER' },
    { value: '1570', label: 'TRANSFORMER MANUFACTURER' },
    { value: '1571', label: 'TRANSLATOR' },
    { value: '1572', label: 'TRANSPORT' },
    { value: '1573', label: 'TRANSPORT AGENCY DIRECTOR' },
    { value: '1574', label: 'TRANSPORT AGENT' },
    { value: '1302', label: 'TRANSPORT COMPANY' },
    { value: '1575', label: 'TRANSPORT OPERATOR' },
    { value: '1303', label: 'TRANSPORT SERVICES' },
    { value: '1304', label: 'TRANSPORT TRADING' },
    { value: '1576', label: 'TRANSPORTATION' },
    { value: '1673', label: 'TRANSPORTATION SUPERVISOR' },
    { value: '1305', label: 'TRANSPORTER' },
    { value: '1577', label: 'TRAVEL AGENCY' },
    { value: '1578', label: 'TRAVEL ASSISTANT' },
    { value: '1306', label: 'TRAVEL CONSULTANT' },
    { value: '1579', label: 'TREASURY EXECUTIVE' },
    { value: '1580', label: 'TRUST EXECUTIVE' },
    { value: '1581', label: 'TUITION TEACHER' },
    { value: '1307', label: 'TUTOR' },
    { value: '1582', label: 'TV ENTERTAINER' },
    { value: '1583', label: 'TV PERSONALITY & ACTRESS' },
    { value: '1308', label: 'TV PRODUCER' },
    { value: '1584', label: 'TYPIST' },
    { value: '1490', label: 'TYRE / TYRE SHOP' },
    { value: '1585', label: 'TYRE & AUTO SERVICES' },
    { value: '1266', label: 'TYRE TRADING' },
    { value: '1586', label: 'TYREMAN' },
    { value: '1587', label: 'UMBRELLA TRADING' },
    { value: '1588', label: 'UNDERTAKER' },
    { value: '1589', label: 'UNEMPLOYED' },
    { value: 'M032', label: 'UNEMPLOYED' },
    { value: '1590', label: 'UNIFORM PERSONNEL' },
    { value: '1591', label: 'UNIT MANAGER' },
    { value: '1592', label: 'UNIT TRUST AGENT' },
    { value: '1593', label: 'UNITED NATION SENIOR OFFICER' },
    { value: '1805', label: 'UNIVERSITY' },
    { value: '1594', label: 'USED CAR DEALER' },
    { value: '1595', label: 'VALUATION ASSISTANT' },
    { value: '1596', label: 'VALUERS' },
    { value: '1597', label: 'VAN DRIVER' },
    { value: '1598', label: 'VCD DISTRUBUTOR' },
    { value: '1310', label: 'VEGETABLE DEALER' },
    { value: '1601', label: 'VEGETABLE FARMER' },
    { value: '1311', label: 'VEGETABLE MERCHANT' },
    { value: '1599', label: 'VEGETABLE SELLER' },
    { value: '1309', label: 'VEGETABLE SUPPLIER /VEGETARIAN' },
    { value: '1600', label: 'VEGETABLE WHOLESELLER' },
    { value: '1603', label: 'VENDOR' },
    { value: '1312', label: 'VENDOR MANAGER' },
    { value: '1604', label: 'VETERINARIAN' },
    { value: '1605', label: 'VICE CHAIRMAN' },
    { value: '1313', label: 'VICE PRESIDENT' },
    { value: '1606', label: 'VIDEO EDITOR' },
    { value: '1314', label: 'VIDEO GRAPHER' },
    { value: '1607', label: 'VIDEO MEN' },
    { value: '1608', label: 'VOICEOVER TALENT' },
    { value: '1609', label: 'WAITER / WAITRESS' },
    { value: '1611', label: 'WARD ATTENDANT' },
    { value: '1315', label: 'WARDEN' },
    { value: '1612', label: 'WARDEN' },
    { value: '1613', label: 'WAREHOUSE ASSISTANT' },
    { value: '1614', label: 'WAREHOUSE MAN' },
    { value: '1316', label: 'WAREHOUSING' },
    { value: '1654', label: 'WARREN OFFICER' },
    { value: '1615', label: 'WATCH COMPONENTS MANUFACTURER' },
    { value: '1616', label: 'WATCH DEALER' },
    { value: '1317', label: 'WATCH SELLER' },
    { value: '1318', label: 'WATCH TRADER' },
    { value: '1618', label: 'WATER TREATMENT PLANT OPERATOR' },
    { value: '1619', label: 'WEB DESIGNER' },
    { value: '1620', label: 'WELDER / WELDING' },
    { value: '1621', label: 'WELDER SITTER' },
    { value: '1622', label: 'WELDING ENGINEER' },
    { value: '1320', label: 'WELDING INSPECTOR' },
    { value: '0349', label: 'WHOLESALER' },
    { value: '1623', label: 'WILL WRITER' },
    { value: '1321', label: 'WIRE FACTORY' },
    { value: '1624', label: 'WIRE HARNES' },
    { value: '1625', label: 'WIREMAN' },
    { value: '1626', label: 'WIREMAN CONTRACTOR' },
    { value: '1628', label: 'WIRING CONTRACTOR' },
    { value: '1627', label: 'WIRING SERVICE' },
    { value: '1629', label: 'WOOD BASED INDUSTRY' },
    { value: '1630', label: 'WOOD DOOR MAKER' },
    { value: '1631', label: 'WOODBOARD CHIP MANUFACTURER' },
    { value: '1632', label: 'WOODEN MOULDING' },
    { value: '1633', label: 'WOODWORK MANUFACTURER' },
    { value: '1634', label: 'WORKER' },
    { value: '1635', label: 'WORKSHOP' },
    { value: '1636', label: 'WORKSHOP & DEALER' },
    { value: '1637', label: 'WORKSHOP MANAGER' },
    { value: '1639', label: 'WORKSHOP OWNER' },
    { value: '1638', label: 'WORKSHOP SUPERVISOR' },
    { value: '1640', label: 'WRITER' }
  ];